extra-deps:
- aeson-1.0.2.1
- bzlib-conduit-0.2.1.5
- binary-0.8.4.1
- cryptohash-sha256-0.11.100.1
- echo-0.1.3
- ed25519-0.0.5.0
- mintty-0.1.1
- mmorph-1.0.9
- optparse-applicative-0.13.0.0
- git: https://github.com/rahulmutt/hpp.git
  commit: 75d74f53a34c875285a665d8878e5b363edfbea5
- git: https://github.com/rahulmutt/zip.git
  commit: a4fbcc9e1efc3e8623022d9fcc83b50d4cdd95a5
- tar-0.5.0.3
- text-1.2.2.1
- turtle-1.3.0
- unix-compat-0.4.3.1
resolver: lts-6.27
flags:
  mintty:
    win32-2-5: false
  eta-repl:
    eta-repl: false
extra-package-dbs: []
packages:
- '.'
# - '../hpp' # Used for local development
# - '../zip'
- codec-jvm
- libraries/eta-boot
- libraries/eta-boot-th
- libraries/eta-meta
- libraries/eta-repl
- utils/eta-pkg
- etlas/etlas
- etlas/etlas-cabal
- etlas/hackage-security/hackage-security
- shake
